LaCasa/LaCasa/Controllers/RestoranController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using LaCasa.EF;
using LaCasa.EntityModels;
using LaCasa.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace LaCasa.Controllers
{
    public class RestoranController : Controller
    {
        private ApplicationDbContext _database;

        public RestoranController(ApplicationDbContext database)
        {
            _database = database;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Poruka()
        {
            return View("Poruka");
        }
        public IActionResult Obrisi(int RestoranID)
        {
            Restoran r = _database.Restorani.Find(RestoranID);

            var recenzijeZaBrisanje = _database.Recenzije.Where(s => s.RestoranID == RestoranID).ToList();

            _database.RemoveRange(recenzijeZaBrisanje);
            _database.SaveChanges();

            _database.Remove(r);
            _database.SaveChanges();

            TempData["PorukaInfo"] = "Uspješno ste obrisali restoran " + r.Naziv;

            return Redirect("/Restoran/Poruka");
        }
        public IActionResult Prikaz(string q)
        {
            var restorani = _database.Restorani
                .Where(s=>q==null || s.Naziv.StartsWith(q))
                .Select(x => new RestoranPrikazVM.Row
            {
                RestoranID = x.RestoranID,
                RegistarskiBroj = x.RegistarskiBroj,
                Adresa = x.Adresa,
                Naziv = x.Naziv,
                RadnoVrijeme = x.RadnoVrijeme,
                Brojtelefona = x.Brojtelefona,
                TipKuhinje = x.TipKuhinje.Naziv
            }).ToList();

            RestoranPrikazVM r = new RestoranPrikazVM();
            r.restorani = restorani;

            return View(r);
        }
        public IActionResult Dodaj(int RestoranID)
        {
            List<SelectListItem> kuhinje = _database.TipKuhinje
                .OrderBy(a => a.Naziv)
                .Select(a => new SelectListItem
                {

                    Value = a.TipKuhinjeID.ToString(),
                    Text = a.Naziv

                }).ToList();

            RestoranDodajVM r;
            if (RestoranID == 0)
            {
                r = new RestoranDodajVM() { };
            }
            else
            {
                r = _database.Restorani
                .Where(w => w.RestoranID == RestoranID)
                .Select(s => new RestoranDodajVM
                {
                    ID = s.RestoranID,
                    RegistarskiBroj = s.RegistarskiBroj,
                    Naziv = s.Naziv,
                    Adresa = s.Adresa,
                    RadnoVrijeme = s.RadnoVrijeme,
                    BrojTelefona = s.Brojtelefona,
                    TipKuhinjeID = s.TipKuhinjeID
                }).Single();
            }

            r.kuhinje = kuhinje;

            return View("Dodaj", r);
        }
        public IActionResult Snimi(RestoranDodajVM r)
        {
            Restoran restoran;

            if (r.ID == 0)
            {
                restoran = new Restoran();
                _database.Add(restoran);
                TempData["PorukaInfo"] = "Uspjesno ste dodali restoran " + restoran.Naziv;
            }
            else
            {
                restoran = _database.Restorani.Find(r.ID);
                TempData["PorukaInfo"] = "Uspjesno ste editovali restoran " + restoran.Naziv;

            }
            restoran.RegistarskiBroj = r.RegistarskiBroj;
            restoran.Naziv = r.Naziv;
            restoran.Adresa = r.Adresa;
            restoran.Brojtelefona = r.BrojTelefona;
            restoran.RadnoVrijeme = r.RadnoVrijeme;
            restoran.TipKuhinjeID = r.TipKuhinjeID;

            _database.SaveChanges();

            return Redirect("/Restoran/Poruka");

        }
    }
}

LaCasa/LaCasa/Views/Restoran/Dodaj.cshtml
@model RestoranDodajVM

    <div class="d-flex justify-content-center">
        <div class="col-md-8 ">
            <h2 class="text-center mb-5">Dodaj restoran</h2>
            <form asp-action="Snimi" asp-controller="Restoran">
                <div style="display:none">
                    <label>Restoran ID</label>
                    <input readonly asp-for="ID" />
                </div>

                <div class="form-row">
                    <div class="col">
                        <div class="form-group">
                            <label>Registarski broj</label>
                            <input class="form-control" asp-for="RegistarskiBroj" />
                        </div>
                    </div>
                    <div class="col">
                        <div class="form-group">
                            <label>Naziv Restorana</label>
                            <input class="form-control" asp-for="Naziv" />
                        </div>
                    </div>
                </div>

                <div class="form-row">
                    <div class="col">
                        <div class="form-group">
                            <label>Adresa</label>
                            <input class="form-control" asp-for="Adresa" />
                        </div>
                    </div>
                    <div class="col">
                        <div class="form-group">
                            <label>Broj Telefona</label>
                            <input class="form-control" asp-for="BrojTelefona" />
                        </div>
                    </div>
                </div>

                <div class="form-row">
                    <div class="col">
                        <div class="form-group">
                            <label>Radno Vrijeme</label>
                            <input class="form-control" asp-for="RadnoVrijeme" />
                        </div>
                    </div>
                    <div class="col">
                        <div class="form-group">
                            <label>Tip Kuhinje</label>
                            <select class="form-control" asp-for="TipKuhinjeID" asp-items="Model.kuhinje"></select>
                        </div>
                    </div>
                </div>
                <input type="submit" class="btn btn-primary" value="Snimi" />
            </form>
        </div>
    </div>

LaCasa/LaCasa/Views/Restoran/Poruka.cshtml
@{

}

@TempData["PorukaInfo"]
<a href="/Restoran/Prikaz"> Idi nazad</a>

LaCasa/LaCasa/Views/Restoran/Prikaz.cshtml
@model RestoranPrikazVM

@{ 
    ViewData["Title"] = "Prikaz";

}

<h1>Prikaz</h1>
<a href="/Restoran/Dodaj" class="btn btn-primary">Dodaj Restoran</a>

<form>
    <input name="q" value="@Model.q" />
    <input type="submit" value="Trazi" />
</form>

<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <th>Naziv</th>
            <th>Adresa</th>
            <th>Broj telefona</th>
            <th>Radno vrijeme</th>
            <th>Tip kuhinje</th>
            <th>Akcija</th>
            <th>Recenzije</th>
            
        </tr>
    </thead>
    <tbody>
        @foreach (RestoranPrikazVM.Row r in Model.restorani)
        {
            <tr>
                <td>@r.Naziv</td> 
                <td>@r.Adresa</td>
                <td>@r.Brojtelefona</td>
                <td>@r.RadnoVrijeme</td>
                <td>@r.TipKuhinje</td>
                <td>
                    <a href="/Restoran/Obrisi?RestoranID=@r.RestoranID" class="btn btn-danger"> Obrisi </a>
                    <a href="/Restoran/Dodaj?RestoranID=@r.RestoranID" class="btn btn-primary"> Uredi </a>

                </td>
                <td>
                    <button onclick="PrikaziRecenzije(@r.RestoranID)" class="btn btn-primary"> Prikazi </button>
                </td>
            </tr>
        }
    </tbody>
</table>

<div id="ajaxPrikaz" style="border:1px solid black"></div>

<script>
    function PrikaziRecenzije(RestoranID) {
        var url = "/Recenzija/Prikaz?RestoranID=" + RestoranID;
        $.get(url, function (d) {
            $("#ajaxPrikaz").html(d);
        });
    }

    function ObrisiRecenziju(RecenzijaID) {
        var url = "/Recenzija/Obrisi?RecenzijaID=" + RecenzijaID;
        $.get(url, function (d) {
            alert("Uspjesno obrisana recenzija");
            $("#ajaxPrikaz").html(d);
        });
    }
    function DodajRecenziju(RestoranID) {
        var url = "/Recenzija/Dodaj?RestoranID=" + RestoranID;
        $.get(url, function (d) {
            $("#ajaxPrikaz").html(d);
        });
    }
    function RecenzijaSnimi() {
        var form = $("#RecenzijaForma");
        var url = "/Recenzija/Snimi";
        $.ajax({
            type: "POST",
            url: url,
            data: form.serialize(),
            success: function (data) {
                $("#ajaxPrikaz").html(data);
            }
        });
    }
</script>