LaCasa/LaCasa/Controllers/KategorijaController.cs
using Data.EntityModels;
using LaCasa.EF;
using LaCasa.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LaCasa.Controllers
{
    public class KategorijaController : Controller
    {
        private ApplicationDbContext _database;

        public KategorijaController(ApplicationDbContext database)
        {
            _database = database;
        }
        public IActionResult Index()
        {
            return View();
        }
        
        public IActionResult Poruka()
        {
            return View("Poruka");
        }
        public IActionResult Obrisi(int KategorijaID)
        {
            Kategorija k = _database.Kategorije.Find(KategorijaID);

            _database.Remove(k);
            _database.SaveChanges();

            TempData["PorukaInfo"] = "Uspješno ste obrisali kategoriju " + k.Naziv;

            return Redirect("/Kategorija/Poruka");
        }
        public IActionResult Prikaz()
        {
            var kategorije = _database.Kategorije.Select(x => new KategorijaPrikazVM.Row
            {
                KategorijaID = x.KategorijaID,
                Naziv = x.Naziv,
                Opis = x.Opis,
            }).ToList();

            KategorijaPrikazVM k = new KategorijaPrikazVM();
            k.kategorije = kategorije;

            return View(k);
        }
        public IActionResult Dodaj(int KategorijaID)
        {
            KategorijaDodajVM k;
            if (KategorijaID == 0)
            {
                k = new KategorijaDodajVM() { };
            }
            else
            {
                k = _database.Kategorije
                .Where(w => w.KategorijaID == KategorijaID)
                .Select(s => new KategorijaDodajVM
                {
                    KategorijaID = s.KategorijaID,
                    Naziv = s.Naziv,
                    Opis = s.Opis,
                }).Single();
            }

            return View("Dodaj", k);
        }
        public IActionResult Snimi(KategorijaDodajVM k)
        {
            Kategorija kategorija;

            if (k.KategorijaID == 0)
            {
                kategorija = new Kategorija();
                _database.Add(kategorija);
                TempData["PorukaInfo"] = "Uspjesno ste dodali kategoriju " + kategorija.Naziv;
            }
            else
            {
                kategorija = _database.Kategorije.Find(k.KategorijaID);
                TempData["PorukaInfo"] = "Uspjesno ste editovali kategoriju " + kategorija.Naziv;
            }
            kategorija.Naziv = k.Naziv;
            kategorija.Opis = k.Opis;

            _database.SaveChanges();

            return Redirect("/Kategorija/Poruka");

        }
    }
}

LaCasa/LaCasa/Views/Kategorija/Dodaj.cshtml
@model KategorijaDodajVM

<div class="d-flex justify-content-center">
    <div class="col-md-8 ">
        <h2 class="text-center mb-5">Dodaj restoran</h2>
        <form asp-action="Snimi" asp-controller="Kategorija">
            <div style="display:none">
                <label>Kategorija ID</label>
                <input readonly asp-for="KategorijaID" />
            </div>

            <div class="form-row">
                <div class="col">
                    <div class="form-group">
                        <label>Naziv</label>
                        <input class="form-control" asp-for="Naziv" />
                    </div>
                </div>
                <div class="col">
                    <div class="form-group">
                        <label>Opis</label>
                        <input class="form-control" asp-for="Opis" />
                    </div>
                </div>
            </div>
            <input type="submit" class="btn btn-primary" value="Snimi" />
        </form>
    </div>
</div>

LaCasa/LaCasa/Views/Kategorija/Poruka.cshtml
@{

}

@TempData["PorukaInfo"]
<a href="/Kategorija/Prikaz"> Idi nazad</a>

LaCasa/LaCasa/Views/Kategorija/Prikaz.cshtml
@model KategorijaPrikazVM

@{ ViewData["Title"] = "Prikaz";

}

<h1>Prikaz kategorija (admin)</h1>
<a href="/Kategorija/Dodaj" class="btn btn-primary mb-4">Dodaj Kategoriju</a>
<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <th>Naziv</th>
            <th>Opis</th>
            <th>Akcija</th>
        </tr>
    </thead>
    <tbody>
        @foreach (KategorijaPrikazVM.Row k in Model.kategorije)
        {
        <tr>
            <td>@k.Naziv</td>
            <td>@k.Opis</td>
            <td>
                <a href="/Kategorija/Obrisi?KategorijaID=@k.KategorijaID" class="btn btn-danger"> Obrisi </a>
                <a href="/Kategorija/Dodaj?KategorijaID=@k.KategorijaID" class="btn btn-primary"> Uredi </a>
            </td>
            <!--
                <td>
                    <button onclick="PrikaziRecenzije(@k.KategorijaID)" class="btn btn-primary"> Prikazi </button>
                </td>
            -->
        </tr>
        }
    </tbody>
</table>